### PR TITLE
MIT, not ISC

### PR DESCRIPTION
**Pull request by dcousens**
The MIT license is typically more explicitly permissive,  which IMHO is preferred.
The intent is the same.

Shouldn't be an issue here,  BUT!
~~@mvayngrib @rubensayshi @fanatid @pernas ACKs required~~

### CODE REVIEW

**Comment by fanatid** [comment]
ack

**Comment by mvayngrib** [comment]
ack

**Comment by dcousens** [comment]
@pernas ? :1st_place_medal:

**Comment by dcousens** [comment]
Actually, when @pernas contributed, it was MIT.  Ha.
https://github.com/dcousens/typeforce/commit/0dff60a3abe9b8de0794b5d9be3c7df8773a9218

Merging...

**Comment by dcousens** [comment]
Same with @rubensayshi

**Comment by dcousens** [comment]
Same with all of you...

Sorry for the mess around! :+1:

**Comment by sha49** [comment]
Sorry guys, I saw that today. ACK

**Pull request merged**
